modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="thitemstages"
version="0.0.6"
displayName="T.H.I.S"
authors="Decursio Team"
logoFile="thitemstages-logo.png"
description='''
Totally Harmonious Item Stages
'''

[[dependencies.thitemstages]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.thitemstages]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,1.19)"
   ordering="NONE"
   side="BOTH"
