modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="thitemstages"
version="0.0.82-hotfix"
displayName="T.H.I.S"
authors="Decursio Team"
logoFile="thitemstages-logo.png"
description='''
Totally Harmonious Item Stages
'''

[[dependencies.thitemstages]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.thitemstages]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="BOTH"
